### ISSUE TITLE
If nothing is specified at the prompt and it is submitted the program exits.

### ISSUE THREAD

**Issue by P94** [P94/key-replace#8]
If no command or macro is specified and it is submitted the program exits with an IndexError. Need to check length of the input variable.

```
user@MacBook-Pro:~/GitHub/key-replace$ ./key-replace.py
Enter macro or command
>
Traceback (most recent call last):
  File "./key-replace.py", line 143, in <module>
    main()
  File "./key-replace.py", line 135, in main
    if input[0] == "/":
IndexError: string index out of range
user@MacBook-Pro:~/GitHub/key-replace$
```

**Comment by P94** [comment]
Issue fixed in commit 75dc73e372f99f9ceaff82423d6b9160b323baee
